name: Sync to Private Repo

on:
  push:
    branches:
      - main  # срабатывает на пуш в ветку main публичного репо

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Клонируем публичный репозиторий
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          repository: madmax179/SS11Labs
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check PRIVATE_REPO_PAT secret
        run: |
          if [ -z "${{ secrets.PRIVATE_REPO_PAT }}" ]; then
            echo "PRIVATE_REPO_PAT is not set!"
            exit 1
          else
            echo "PRIVATE_REPO_PAT is set."
          fi
      
      # 2️⃣ Добавляем приватный репо как remote
      - name: Add private repo remote
        env:
          PRIVATE_REPO_PAT: ${{secrets.PRIVATE_REPO_PAT}}
        run:
          git remote remove private
          git remote add private https://x-access-token:$PRIVATE_REPO_PAT@github.com/AlexeyIzosimov/SS11Labs_private.git

      # 3️⃣ Пушим изменения в приватный репо
      - name: Push to private repo
        run: git push private main --force
